const map=L.map('map',{zoomControl:true}).setView([19.38,-99.14],11);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map);
let data=[],filtered=[],markers=L.layerGroup().addTo(map),boroughLayer=null,boroughByName={},selectedRecord=null,selectedMarker=null;
const metrics={pct_sobrepeso_obesidad:{label:'Sobrepeso u obesidad',unit:'%'},pct_caries:{label:'Caries',unit:'%'},pct_visual:{label:'Problemas visuales',unit:'%'},imc_promedio:{label:'IMC promedio',unit:''},completitud:{label:'Completitud',unit:'%'},prioridad_atencion:{label:'Prioridad de atención',unit:''},alertas_promedio:{label:'Alertas múltiples',unit:''}};
const palette=['#2f7d68','#e0b64b','#d67a34','#a83c4a'];
const $=id=>document.getElementById(id);
function text(v){return v===null||v===undefined||String(v).trim()===''?'Sin dato':String(v)}
function num(v,d=1){return v==null||v===''||Number.isNaN(+v)?'Sin dato':(+v).toLocaleString('es-MX',{maximumFractionDigits:d})}
function currentMetric(){return $('queryGroup').value==='priority'?'prioridad_atencion':$('queryGroup').value==='alerts'?'alertas_promedio':$('healthMetric').value}
function values(metric,rows=data){return rows.map(r=>+r[metric]).filter(Number.isFinite).sort((a,b)=>a-b)}
function qs(metric){const a=values(metric);if(!a.length)return[0,0,0];const q=p=>a[Math.min(a.length-1,Math.floor((a.length-1)*p))];return[q(.25),q(.5),q(.75)]}
function category(v,m){if(v==null||v===''||!Number.isFinite(+v))return'Sin dato';const q=qs(m),x=+v;return x<=q[0]?'Bajo':x<=q[1]?'Medio':x<=q[2]?'Alto':'Muy alto'}
function color(v,m){const c=category(v,m);return c==='Sin dato'?'#8b98a1':palette[['Bajo','Medio','Alto','Muy alto'].indexOf(c)]}
function populate(){[...new Set(data.map(x=>x.alcaldia).filter(Boolean))].sort().forEach(v=>$('filterAlcaldia').add(new Option(v,v)));[...new Set(data.map(x=>x.REF_CICLO_ESCOLAR).filter(Boolean))].sort().forEach(v=>$('filterCycle').add(new Option(v,v)));data.forEach(r=>{$('cctList').append(new Option('',r.CVE_ESCUELA_ATENCION));$('nameList').append(new Option('',r.NOM_ESCUELA_ATENCION))})}
function apply(){const m=currentMetric();filtered=data.filter(r=>(!$('filterAlcaldia').value||r.alcaldia===$('filterAlcaldia').value)&&(!$('filterCycle').value||r.REF_CICLO_ESCOLAR===$('filterCycle').value)&&(!$('searchCct').value||text(r.CVE_ESCUELA_ATENCION).toUpperCase().includes($('searchCct').value.toUpperCase()))&&(!$('searchName').value||text(r.NOM_ESCUELA_ATENCION).toUpperCase().includes($('searchName').value.toUpperCase()))&&(!$('filterPriority').value||category(r.prioridad_atencion,'prioridad_atencion')===$('filterPriority').value)&&(!$('filterAlerts').value||category(r.alertas_promedio,'alertas_promedio')===$('filterAlerts').value));render(m);updateActiveFilters();if(selectedRecord){const stillVisible=filtered.includes(selectedRecord);if(stillVisible)showDetail(selectedRecord,m,false);else clearSelection()}}
function render(m){markers.clearLayers();selectedMarker=null;filtered.forEach(r=>{if(!Number.isFinite(+r.latitud)||!Number.isFinite(+r.longitud))return;const marker=L.circleMarker([+r.latitud,+r.longitud],{radius:6.5,weight:1.5,color:'#fff',fillColor:color(r[m],m),fillOpacity:.92});marker.bindTooltip(`<strong>${text(r.NOM_ESCUELA_ATENCION)}</strong><br>${text(r.CVE_ESCUELA_ATENCION)}`,{direction:'top'});marker.on('click',()=>showDetail(r,currentMetric(),true));if(selectedRecord===r){selectedMarker=marker;marker.setStyle({radius:9,weight:3,color:'#173347'})}marker.addTo(markers)});updateLegend(m);updateKpis(m);updateBoroughSummary(m)}
function updateLegend(m){const q=qs(m),u=metrics[m].unit||'',d=m==='imc_promedio'?1:1;const f=v=>num(v,d)+u;$('legendTitle').textContent='Clasificación por '+metrics[m].label.toLowerCase();const ranges=[`Hasta ${f(q[0])}`,`Más de ${f(q[0])} y hasta ${f(q[1])}`,`Más de ${f(q[1])} y hasta ${f(q[2])}`,`Más de ${f(q[2])}`];$('legendBody').innerHTML='<p class="legend-note">Los colores separan los registros en cuatro grupos de tamaño similar (cuartiles). Los límites se muestran redondeados; la clasificación conserva los valores exactos.</p>'+['Bajo','Medio','Alto','Muy alto'].map((c,i)=>`<div class="legend-row"><span class="dot" style="background:${palette[i]}"></span><span>${c}</span><small>${ranges[i]}</small></div>`).join('')+'<div class="legend-row"><span class="dot" style="background:#8b98a1"></span><span>Sin dato</span><small>Registro sin valor</small></div>'}
function avg(col,rows=filtered){const a=rows.map(r=>+r[col]).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function enrollment(r){return +r.NUM_MATRICULA_TOTAL_ESCUELA_x||+r.NUM_MATRICULA_TOTAL_ESCUELA_y||+r.matricula||0}
function updateKpis(m){$('kSchools').textContent=filtered.length.toLocaleString('es-MX');$('kEnrollment').textContent=filtered.reduce((s,r)=>s+enrollment(r),0).toLocaleString('es-MX');$('kImc').textContent=num(avg('imc_promedio'),2);$('kMetric').textContent=num(avg(m),2)+(metrics[m].unit||'');$('kMetricLabel').textContent='Promedio: '+metrics[m].label}
function infoText(label,value){return `<div class="info"><small>${label}</small><strong>${text(value)}</strong></div>`}
function infoNum(label,value,unit=''){return `<div class="info"><small>${label}</small><strong>${num(value,2)}${value==null||value===''||Number.isNaN(+value)?'':unit}</strong></div>`}
function showDetail(r,m,focus=true){selectedRecord=r;if(focus){markers.eachLayer(layer=>layer.setStyle&&layer.setStyle({radius:6.5,weight:1.5,color:'#fff'}));const found=[];markers.eachLayer(layer=>{const ll=layer.getLatLng&&layer.getLatLng();if(ll&&Math.abs(ll.lat-(+r.latitud))<1e-8&&Math.abs(ll.lng-(+r.longitud))<1e-8)found.push(layer)});selectedMarker=found[0]||null;if(selectedMarker)selectedMarker.setStyle({radius:9,weight:3,color:'#173347'})}$('detailTitle').textContent=text(r.NOM_ESCUELA_ATENCION);const cat=category(r[m],m),bg=color(r[m],m);$('detailBody').innerHTML=`<div class="selected-context"><span>Indicador mostrado</span><strong>${metrics[m].label}</strong><small>La ficha cambia automáticamente al modificar el indicador del mapa.</small></div><div class="info-grid">${infoText('CCT',r.CVE_ESCUELA_ATENCION)}${infoText('Turno',r.REF_TURNO_ATENCION)}${infoText('Ciclo',r.REF_CICLO_ESCOLAR)}${infoNum('Matrícula',enrollment(r))}${infoText('Alcaldía',r.alcaldia)}</div><h3 class="section-title">Indicadores de salud</h3><div class="info-grid">${infoNum('IMC promedio',r.imc_promedio)}${infoNum('Sobrepeso u obesidad',r.pct_sobrepeso_obesidad,'%')}${infoNum('Caries',r.pct_caries,'%')}${infoNum('Problemas visuales',r.pct_visual,'%')}${infoNum('Alertas múltiples',r.alertas_promedio)}${infoNum('Prioridad de atención',r.prioridad_atencion)}${infoNum('Completitud',r.completitud,'%')}</div><h3 class="section-title">Clasificación del indicador activo</h3><div class="semaphore" style="background:${bg}"><span>${metrics[m].label}</span><strong>${cat}</strong><small>${num(r[m],2)}${metrics[m].unit}</small></div>`;$('detail').classList.add('open')}
function updateBoroughSummary(m){const groups={};filtered.forEach(r=>{const k=r.alcaldia||'SIN ALCALDÍA';(groups[k]??=[]).push(r)});$('boroughSummary').innerHTML=Object.entries(groups).sort((a,b)=>a[0].localeCompare(b[0])).map(([name,rows])=>`<button class="borough-card" data-borough="${name}"><span><strong>${name}</strong><small>${rows.length.toLocaleString('es-MX')} registros · ${rows.reduce((s,r)=>s+enrollment(r),0).toLocaleString('es-MX')} matrícula</small></span><b>${num(avg(m,rows),2)}${metrics[m].unit}</b></button>`).join('');document.querySelectorAll('.borough-card').forEach(b=>b.addEventListener('click',()=>{$('filterAlcaldia').value=b.dataset.borough;zoomToBorough(b.dataset.borough);apply()}))}

function clearSelection(){selectedRecord=null;selectedMarker=null;$('detail').classList.remove('open')}
function updateActiveFilters(){const items=[];if($('filterAlcaldia').value)items.push('Alcaldía: '+$('filterAlcaldia').value);if($('filterCycle').value)items.push('Ciclo: '+$('filterCycle').value);if($('filterPriority').value)items.push('Prioridad: '+$('filterPriority').value);if($('filterAlerts').value)items.push('Alertas: '+$('filterAlerts').value);if($('searchCct').value)items.push('CCT: '+$('searchCct').value);if($('searchName').value)items.push('Escuela: '+$('searchName').value);$('activeFilters').innerHTML=items.length?'<span class="filter-caption">Filtros activos</span>'+items.map(v=>'<span class="filter-chip">'+v+'</span>').join(''):'<span class="no-filters">Sin filtros activos</span>'}
function updateActiveMetric(){const m=currentMetric();$('activeMetricName').textContent=metrics[m].label}

function normName(v){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function loadBoroughs(){fetch('data/alcaldias.json').then(r=>r.json()).then(g=>{boroughLayer=L.geoJSON(g,{style:{color:'#496675',weight:1.5,fillColor:'#5e8292',fillOpacity:.06},onEachFeature:(f,l)=>{const props=f.properties||{};const name=props.NOMGEO||props.alcaldia||props.ALCALDIA||props.nombre||props.NOMBRE||Object.values(props).find(v=>typeof v==='string');if(name){boroughByName[normName(name)]=l}}}).addTo(map)}).catch(()=>{})}
function zoomToBorough(name){const layer=boroughByName[normName(name)];if(layer)map.fitBounds(layer.getBounds(),{padding:[25,25],maxZoom:13});else{const pts=data.filter(r=>r.alcaldia===name&&Number.isFinite(+r.latitud)&&Number.isFinite(+r.longitud)).map(r=>[+r.latitud,+r.longitud]);if(pts.length)map.fitBounds(pts,{padding:[25,25],maxZoom:13})}}
$('queryGroup').onchange=()=>{$('healthWrap').classList.toggle('hidden',$('queryGroup').value!=='health');updateActiveMetric();apply()};$('healthMetric').onchange=()=>{updateActiveMetric();apply()};$('clearFilters').onclick=()=>{[$('filterAlcaldia'),$('filterCycle'),$('filterPriority'),$('filterAlerts')].forEach(x=>x.value='');$('searchCct').value='';$('searchName').value='';apply();map.setView([19.38,-99.14],11)};$('filterAlcaldia').addEventListener('change',()=>{if($('filterAlcaldia').value)zoomToBorough($('filterAlcaldia').value);apply()});['filterCycle','filterPriority','filterAlerts'].forEach(id=>$(id).addEventListener('change',apply));$('closeDetail').onclick=clearSelection;$('hideMenu').onclick=()=>{$('sidebar').classList.add('hidden');$('showMenu').classList.remove('hidden');map.invalidateSize()};$('showMenu').onclick=()=>{$('sidebar').classList.remove('hidden');$('showMenu').classList.add('hidden');map.invalidateSize()};$('toggleLegend').onclick=()=>{const body=$('legendBody');body.classList.toggle('hidden');$('toggleLegend').textContent=body.classList.contains('hidden')?'+':'−'};$('toggleBoroughSummary').onclick=()=>{const body=$('boroughSummary');body.classList.toggle('hidden');$('toggleBoroughSummary').textContent=body.classList.contains('hidden')?'+':'−'};
$('searchCct').onchange=()=>{apply();const r=filtered.find(x=>x.CVE_ESCUELA_ATENCION===$('searchCct').value);if(r){map.setView([r.latitud,r.longitud],16);showDetail(r,currentMetric(),true)}};$('searchName').onchange=()=>{apply();const r=filtered.find(x=>x.NOM_ESCUELA_ATENCION===$('searchName').value);if(r){map.setView([r.latitud,r.longitud],16);showDetail(r,currentMetric(),true)}};
Promise.all([fetch('data/salud_escolar.json').then(r=>r.json())]).then(([d])=>{data=d;filtered=d;populate();loadBoroughs();updateActiveMetric();updateActiveFilters();apply()}).catch(e=>alert('No fue posible cargar la base de salud: '+e));
